#!/bin/sh

unset PWD APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL USER ITERM_PROFILE LC_TERMINAL_VERSION LANG COMMAND_MODE __CFBundleIdentifier LOGNAME TERM PATH ZSH TERM_SESSION_ID SHLVL TERM_PROGRAM_VERSION PAGER SSH_AUTH_SOCK COLORTERM HOME SHELL LESS __CF_USER_TEXT_ENCODING COLORFGBG LSCOLORS LC_TERMINAL TERM_PROGRAM TMPDIR ITERM_SESSION_ID XPC_SERVICE_NAME XPC_FLAGS ORIGINAL_XDG_CURRENT_DESKTOP VSCODE_GIT_IPC_HANDLE GIT_ASKPASS VSCODE_GIT_ASKPASS_NODE VSCODE_GIT_ASKPASS_MAIN OLDPWD _

REQUEST_DATA="name=Test&email=GOOD"

# PATH_INFO="/test_cgi/post/action.php"
# REQUEST_METHOD="POST"
# PATH_TRANSLATED="./www/test_cgi/post/action.php"
# REDIRECT_STATUS="200"
# QUERY_STRING=""
# SERVER_PROTOCOL="HTTP/1.1"
# SCRIPT_FILENAME="./www/test_cgi/post/action.php"
# CONTENT_TYPE="application/x-www-form-urlencoded"
# CONTENT_LENGTH=${#REQUEST_DATA}
# GATEWAY_INTERFACE="CGI/1.1"
# SERVER_SOFTWARE="Webserv/1.0"

CONTENT_LENGTH="${#REQUEST_DATA}"
CONTENT_TYPE="application/x-www-form-urlencoded"
GATEWAY_INTERFACE="CGI/1.1"
PATH_INFO="/action.php"
PATH_TRANSLATED="/action.php"
QUERY_STRING=""
REDIRECT_STATUS="200"
REMOTE_IDENT=""
REMOTE_USER=""
REMOTEaddr="0"
REQUEST_METHOD="POST"
REQUEST_URI="/action.php"
SCRIPT_FILENAME="./www/test_cgi/post/action.php"
SCRIPT_NAME="./www/test_cgi/post/action.php"
SERVER_NAME="0"
SERVER_PORT="8081"
SERVER_PROTOCOL="HTTP/1.1"
SERVER_SOFTWARE="Weebserv/1.0"

export CONTENT_LENGTH
export CONTENT_TYPE
export GATEWAY_INTERFACE
export PATH_INFO
export PATH_TRANSLATED
export QUERY_STRING
export REDIRECT_STATUS
export REMOTE_IDENT
export REMOTE_USER
export REMOTEaddr
export REQUEST_METHOD
export REQUEST_URI
export SCRIPT_FILENAME
export SCRIPT_NAME
export SERVER_NAME
export SERVER_PORT
export SERVER_PROTOCOL
export SERVER_SOFTWARE

# export PATH_INFO
# export REQUEST_METHOD
# export PATH_TRANSLATED
# export REDIRECT_STATUS
# export QUERY_STRING
# export SERVER_PROTOCOL
# export SCRIPT_FILENAME
# export CONTENT_TYPE
# export CONTENT_LENGTH
# export GATEWAY_INTERFACE
# export SERVER_SOFTWARE

echo $REQUEST_DATA | www/bin/php-cgi